[style.description]
foreground = { rgb = [224, 226, 239] }
underline = false
bold = false
italic = false

[style.command_name]
foreground = { rgb = [177, 197, 255] }
underline = false
bold = true
italic = false

[style.example_text]
foreground = { rgb = [196, 195, 235] }
underline = false
bold = false
italic = false

[style.example_code]
foreground = { rgb = [224, 226, 239] }
underline = false
bold = false
italic = false

[style.example_variable]
foreground = { rgb = [207, 190, 246] }
underline = true
bold = false
italic = false

[display]
compact = false
use_pager = false
show_title = false

[updates]
auto_update = false
auto_update_interval_hours = 720
archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download/"
tls_backend = "rustls-with-webpki-roots"

[directories]

[search]
