# ~/.config/ghostty/colors-template.conf
background = #040e11
foreground = #d8e5e9
palette = 0=#091518
palette = 1=#ffb4ab
palette = 2=#00d9fd
palette = 3=#a5caf5
palette = 4=#a8cbe2
palette = 5=#006375
palette = 6=#ffffff
palette = 7=#bcc9cd
palette = 8=#515e61
palette = 9=#ffb4ab
palette = 10=#00d9fd
palette = 11=#a5caf5
palette = 12=#a8cbe2
palette = 13=#006375
palette = 14=#ffffff
palette = 15=#d8e5e9
background-opacity = 0.92
