# ~/.config/ghostty/colors-template.conf
background = #0e141c
foreground = #dde3ee
palette = 0=#0e141c
palette = 1=#ffb4ab
palette = 2=#a1c9ff
palette = 3=#c2c1f9
palette = 4=#bbc6ea
palette = 5=#005ca0
palette = 6=#ffffff
palette = 7=#c1c7d2
palette = 8=#565c66
palette = 9=#ffb4ab
palette = 10=#a1c9ff
palette = 11=#c2c1f9
palette = 12=#bbc6ea
palette = 13=#005ca0
palette = 14=#ffffff
palette = 15=#dde3ee
