# ~/.config/ghostty/colors-template.conf
background = #070d15
foreground = #dee2ee
palette = 0=#0e141c
palette = 1=#ffb4ab
palette = 2=#a3c9ff
palette = 3=#c4c1f9
palette = 4=#bcc5eb
palette = 5=#005ca3
palette = 6=#ffffff
palette = 7=#c1c7d2
palette = 8=#565c66
palette = 9=#ffb4ab
palette = 10=#a3c9ff
palette = 11=#c4c1f9
palette = 12=#bcc5eb
palette = 13=#005ca3
palette = 14=#ffffff
palette = 15=#dee2ee
background-opacity = 0.92
