# new windows
keybind = ctrl+shift+t=new_window
keybind = alt+n=new_tab
keybind = alt+tab=next_tab

# new split
keybind = shift+alt+h=new_split:left
keybind = shift+alt+j=new_split:down
keybind = shift+alt+k=new_split:up
keybind = shift+alt+l=new_split:right
keybind = shift+alt+n=new_split:auto

# goto split
keybind = alt+h=goto_split:left
keybind = alt+j=goto_split:down
keybind = alt+k=goto_split:up
keybind = alt+l=goto_split:right


# resize split
keybind = shift+ctrl+h=resize_split:left,30
keybind = shift+ctrl+j=resize_split:down,30
keybind = shift+ctrl+k=resize_split:up,30
keybind = shift+ctrl+l=resize_split:right,30

# closw split
keybind = alt+w=close_surface

# max / resume split
keybind = alt+m=toggle_split_zoom
keybind = alt+f=toggle_split_zoom

# divide all splits equally
keybind = ctrl+shift+equal=equalize_splits

# scroll page
keybind = alt+u=scroll_page_down
keybind = alt+i=scroll_page_up

keybind = shift+ctrl+r=reload_config
keybind = shift+ctrl+o=inspector:toggle

# toggle quick terminal
keybind = global:cmd+backquote=toggle_quick_terminal

