# ~/.config/hypr/colors-template.conf
$active_border = rgba({{colors.primary.default.hex_stripped}}ff) rgba({{colors.primary_container.default.hex_stripped}}8e) 30deg
$inactive_border = rgba({{colors.surface_variant.default.hex_stripped}}aa)
