"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#ffb1c4)\
[ ](bg:#ffb1c4 fg:#5c0029)\
[](bg:#f5b7b3 fg:#ffb1c4)\
$directory\
[](fg:#f5b7b3 bg:#b50057)\
$git_branch\
$git_status\
[](fg:#b50057 bg:#38282c)\
$nodejs\
$rust\
$golang\
$lua\
$c\
$php\
[](fg:#38282c bg:#2d1e21)\
$time\
[ ](fg:#2d1e21)\
\n$character""" 

[directory]
style = "fg:#46201f bg:#f5b7b3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#b50057"
format = '[[ $symbol $branch ](fg:#f5b7b3 bg:#b50057)]($style)'

[git_status]
style = "bg:#b50057"
format = '[[($all_status$ahead_behind )](fg:#f5b7b3 bg:#b50057)]($style)'

[python]
symbol = " "
style = "bg:#38282c"
format = '[[ $symbol ($version) ( \($virtualenv\) )](fg:#f5b7b3 bg:#38282c)]($style)'

[java]
symbol = " "
style = "bg:#38282c"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#38282c)]($style)'

[rust]
symbol = " "
style = "bg:#38282c"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#38282c)]($style)'

[nodejs]
symbol = " "
style = "bg:#38282c"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#38282c)]($style)'

[golang]
symbol = " "
style = "bg:#38282c"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#38282c)]($style)'

[lua]
symbol = " "
style = "bg:#38282c"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#38282c)]($style)'

[c]
symbol = " "
style = "bg:#38282c"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#38282c)]($style)'

[docker_context]
symbol = " "
style = "bg:#2d1e21"
format = '[[ $symbol $context ](fg:#d9c0c5 bg:#2d1e21)]($style)'

[cmd_duration]
min_time = 2000
style = "bg:#2d1e21"
format = '[[ 󱎫 $duration ](fg:#d9c0c5 bg:#2d1e21)]($style)'

[time]
disabled = false
time_format = "%R" 
style = "bg:#2d1e21"
format = '[[  $time ](fg:#d9c0c5 bg:#2d1e21)]($style)'

[character]
success_symbol = "[](bold fg:#ffb1c4) "
error_symbol = "[](bold fg:#ffb4ab) "
vimcmd_symbol = "[](bold fg:#f5b7b3)"
