"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a1c9ff)\
[ ](bg:#a1c9ff fg:#002c51)\
[](bg:#bbc6ea fg:#a1c9ff)\
$directory\
[](fg:#bbc6ea bg:#005ea2)\
$git_branch\
$git_status\
[](fg:#005ea2 bg:#272d36)\
$nodejs\
$rust\
$golang\
$lua\
$c\
$php\
[](fg:#272d36 bg:#1c222b)\
$time\
[ ](fg:#1c222b)\
\n$character""" 

[directory]
style = "fg:#1f2a47 bg:#bbc6ea"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#005ea2"
format = '[[ $symbol $branch ](fg:#bbc6ea bg:#005ea2)]($style)'

[git_status]
style = "bg:#005ea2"
format = '[[($all_status$ahead_behind )](fg:#bbc6ea bg:#005ea2)]($style)'

[python]
symbol = " "
style = "bg:#272d36"
format = '[[ $symbol ($version) ( \($virtualenv\) )](fg:#bbc6ea bg:#272d36)]($style)'

[java]
symbol = " "
style = "bg:#272d36"
format = '[[ $symbol ($version) ](fg:#bbc6ea bg:#272d36)]($style)'

[rust]
symbol = " "
style = "bg:#272d36"
format = '[[ $symbol ($version) ](fg:#bbc6ea bg:#272d36)]($style)'

[nodejs]
symbol = " "
style = "bg:#272d36"
format = '[[ $symbol ($version) ](fg:#bbc6ea bg:#272d36)]($style)'

[golang]
symbol = " "
style = "bg:#272d36"
format = '[[ $symbol ($version) ](fg:#bbc6ea bg:#272d36)]($style)'

[lua]
symbol = " "
style = "bg:#272d36"
format = '[[ $symbol ($version) ](fg:#bbc6ea bg:#272d36)]($style)'

[c]
symbol = " "
style = "bg:#272d36"
format = '[[ $symbol ($version) ](fg:#bbc6ea bg:#272d36)]($style)'

[docker_context]
symbol = " "
style = "bg:#1c222b"
format = '[[ $symbol $context ](fg:#c1c7d2 bg:#1c222b)]($style)'

[cmd_duration]
min_time = 2000
style = "bg:#1c222b"
format = '[[ 󱎫 $duration ](fg:#c1c7d2 bg:#1c222b)]($style)'

[time]
disabled = false
time_format = "%R" 
style = "bg:#1c222b"
format = '[[  $time ](fg:#c1c7d2 bg:#1c222b)]($style)'

[character]
success_symbol = "[](bold fg:#a1c9ff) "
error_symbol = "[](bold fg:#ffb4ab) "
vimcmd_symbol = "[](bold fg:#bbc6ea)"
