"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#ffb1c4)\
[ ](bg:#ffb1c4 fg:#65002e)\
[](bg:#f5b7b3 fg:#ffb1c4)\
$directory\
[](fg:#f5b7b3 bg:#8f0043)\
$git_branch\
$git_status\
[](fg:#8f0043 bg:#352629)\
$nodejs\
$rust\
$golang\
$lua\
$c\
$php\
[](fg:#352629 bg:#2a1c1f)\
$time\
[ ](fg:#2a1c1f)\
\n$character""" 

[directory]
style = "fg:#4c2523 bg:#f5b7b3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#8f0043"
format = '[[ $symbol $branch ](fg:#f5b7b3 bg:#8f0043)]($style)'

[git_status]
style = "bg:#8f0043"
format = '[[($all_status$ahead_behind )](fg:#f5b7b3 bg:#8f0043)]($style)'

[python]
symbol = " "
style = "bg:#352629"
format = '[[ $symbol ($version) ( \($virtualenv\) )](fg:#f5b7b3 bg:#352629)]($style)'

[java]
symbol = " "
style = "bg:#352629"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#352629)]($style)'

[rust]
symbol = " "
style = "bg:#352629"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#352629)]($style)'

[nodejs]
symbol = " "
style = "bg:#352629"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#352629)]($style)'

[golang]
symbol = " "
style = "bg:#352629"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#352629)]($style)'

[lua]
symbol = " "
style = "bg:#352629"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#352629)]($style)'

[c]
symbol = " "
style = "bg:#352629"
format = '[[ $symbol ($version) ](fg:#f5b7b3 bg:#352629)]($style)'

[docker_context]
symbol = " "
style = "bg:#2a1c1f"
format = '[[ $symbol $context ](fg:#d9c0c5 bg:#2a1c1f)]($style)'

[cmd_duration]
min_time = 2000
style = "bg:#2a1c1f"
format = '[[ 󱎫 $duration ](fg:#d9c0c5 bg:#2a1c1f)]($style)'

[time]
disabled = false
time_format = "%R" 
style = "bg:#2a1c1f"
format = '[[  $time ](fg:#d9c0c5 bg:#2a1c1f)]($style)'

[character]
success_symbol = "[](bold green) "
error_symbol = "[](bold red) "
vimcmd_symbol = "[](bold blue)"
